<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Активно',
    'An error occurred Item has not been restored.' => 'Возникла ошибка. Запись не восстановлена.',
    'An error occurred while attempting to hide record.' => 'Возникла ошибка при попытке скрыть запись.',
    'An error occurred while deleting record.' => 'Возникла ошибка при удалении записи.',
    'An error occurred while saving {model}!' => 'Возникла ошибка при сохранении {model}!',
    'Class Name' => 'Имя класса',
    'Context ID' => 'Контекст',
    'Default Items Per Page' => 'Элементов на странице по умолчанию',
    'Delete' => 'Удалить',
    'Deleted' => 'Удаленные',
    'Edit' => 'Редактировать',
    'Edit {title}' => 'Редактируем {title}',
    'Entities list' => 'Список элементов',
    'Entities management' => 'Управление элементами',
    'Entities tree' => 'Дерево сущностей',
    'Entity ID' => 'ID элемента',
    'Expand In Tree' => 'Раскрывать в дереве',
    'ID' => 'ID',
    'Invalid entity id #{id}' => 'Неизвестный id сущности #{id}',
    'Is Active' => 'Активен',
    'Main options' => 'Основные настройки',
    'Missing parameter {param}' => 'Отсутствует параметр {param}',
    'Name' => 'Название',
    'New' => 'Создать',
    'New entity' => 'Новый элемент',
    'Page not found' => 'Страница не найдена',
    'Properties' => 'Свойства',
    'Parent ID' => 'Родитель',
    'Please verify that all fields are filled correctly!' => 'Пожалуйста, проверьте, чтобы все поля были корректно заполнены!',
    'Record has been successfully deleted.' => 'Запись была успешно удалена.',
    'Record has been successfully hidden.' => 'Запись была успешно скрыта.',
    'Record has been successfully restored.' => 'Запись была успешно восстановлена.',
    'Record with id {id} not found!' => 'Запись с id {id} не найдена!',
    'Restore' => 'Восстановить',
    'Route' => 'Маршрут',
    'Save' => 'Сохранить',
    'Search for a parent ...' => 'Найти родителя...',
    'Show Hidden Records In Tree' => 'Показывать скрытые записи в дереве',
    'Show all' => 'Показывать все',
    'Show deleted?' => 'Что показывать?',
    'Show only active' => 'Только активные',
    'Show only deleted' => 'Только удаленные',
    'Sort Order' => 'Сортировка',
    'The \'entityClass\' must use \'DevGroup\\Entity\\traits\\SoftDeleteTrait\'!' => 'Класс \'entityClass\' должен использовать \'DevGroup\\Entity\\traits\\SoftDeleteTrait\'!',
    'The following columns \'{columns}\' are not found in database table!' => 'Колонка(и) \'{columns}\' не найдены в таблице базы данных',
    'Unknown entity class \'{class}\'.' => 'Неизвестный класс сущности \'{class}\'.',
    'Value \'{value}\' already in use, please, choose another!' => 'Значение \'{value}\' уже занято, пожалуйста, выберите другое!',
    '{model} not found!' => '{model} не найдена!',
    '{model} successfully saved!' => 'Запись \'{model}\' успешно сохранена!',
];
